# Required items:
dataIdScanPath: '/project/rubintv/dataIds'
bucketName: 'rubintv_data_tts'
dimensionUniverseFile: '/project/rubintv/butlerDimensionUniverse.json'

# Summit items:
nightReportPath:     '/project/rubintv/nightReportData'

# AuxTel metadata
auxTelMetadataPath: '/project/rubintv/sidecar_metadata'
auxTelMetadataShardPath: '/project/rubintv/sidecar_metadata/shards'

# all sky
allSkyRootDataPath: '/project/rubintv/allsky/raw'
allSkyOutputPath: '/project/rubintv/allsky'

# animation
moviePngPath: '/project/rubintv/auxTel_animation'

# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
# astrometryNetRefCatPath: '/project/shared/ref_cats/astrometry_net'

# ComCam configuration:
comCamButlerPath: /repo/LSSTComCam/butler.yaml
binning: 8
# # paths for serving TS8 metadata at SLAC
comCamMetadataPath: /project/rubintv/LSSTComCam/sidecar_metadata
comCamMetadataShardPath: /project/rubintv/LSSTComCam/sidecar_metadata/shards

comCamSimMetadataPath: /project/rubintv/LSSTComCamSim/sidecar_metadata
comCamSimMetadataShardPath: /project/rubintv/LSSTComCamSim/sidecar_metadata/shards

comCamSimAosMetadataPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata
comCamSimAosMetadataShardPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata/shards

comCamAosMetadataPath: /project/rubintv/LSSTComCamAos/sidecar_metadata
comCamAosMetadataShardPath: /project/rubintv/LSSTComCamAos/sidecar_metadata/shards

lsstCamMetadataPath: /project/rubintv/LSSTCam/sidecar_metadata
lsstCamMetadataShardPath: /project/rubintv/LSSTCam/sidecar_metadata/shards
lsstCamButlerPath: /repo/LSSTCam/butler.yaml

# Not prefixed with ComCam because we're currently just pretending that ComCam is TS8
scratchPath: '/project/rubintv/LSSTComCam'
plotPath: '/project/rubintv/LSSTComCam/plots'
calculatedDataPath: '/project/rubintv/calculatedData'
binnedCalexpPath: /project/rubintv/calculatedData/calexps

# TMA config:
tmaMetadataPath: '/project/rubintv/tma/sidecar_metadata'
tmaMetadataShardPath: '/project/rubintv/tma/sidecar_metadata/shards'

sfmPipelineFile:
  LSSTComCamSim: $DRP_PIPE_DIR/pipelines/LSSTComCamSim/quickLook.yaml
  LSSTComCam: $DRP_PIPE_DIR/pipelines/LSSTComCam/quickLook.yaml
  LSSTCam: $DRP_PIPE_DIR/pipelines/LSSTCam/quickLook.yaml

aosPipelineFile:
  LSSTComCamSim: $TS_WEP_DIR/pipelines/production/comCamSimRapidAnalysisPipeline.yaml
  LSSTComCam: $TS_WEP_DIR/pipelines/production/comCamRapidAnalysisPipeline.yaml

outputChains:
  LSSTComCam: LSSTComCam/quickLook
  LSSTComCamSim: LSSTComCamSim/quickLook
  LSSTCam: LSSTCam/quickLook


### not applicable on the TTS but here explicitly to keep keys the same:
# they also need to exist for the LocationConfig to init correctly as it checks
starTrackerDataPath: '/project'
starTrackerOutputPath: '/project'
starTrackerMetadataShardPath: '/project'
starTrackerMetadataPath: '/project'
astrometryNetRefCatPath: '/project'
