# metadata
metadataOutputRoot: "/project/rubintv/sidecar_metadata/"

# all sky
allSkyRootDataPath: "/project/rubintv/allsky/raw/"
allSkyOutputRoot: "/project/rubintv/allsky/"

# animation
moviePngRoot: "/project/rubintv/auxTel_animation/"

# Star Trackers
starTrackerDataPath: "/project/"
starTrackerMetadataRoot: "/project/rubintv/starTracker/sidecar_metadata/"
starTrackerOutputRoot: "/project/rubintv/starTracker/output/"
astrometryNetRefCatRoot: "/project/shared/ref_cats/astrometry_net/"
