# Required items:
dataIdScanPath: '/scratch/rubintv/dataIds'
bucketName: 'rubintv_data_slac'

# Butler paths - use full paths not aliases here as path existence is checked
ts8ButlerPath: '/repo/ir2/butler.yaml'
botButlerPath: '/repo/ir2/butler.yaml'

# # data paths
scratchPath: '/scratch/rubintv'
plotPath: '/scratch/rubintv/plots'
calculatedDataPath: '/scratch/rubintv/calculatedData'

# # paths for serving TS8 metadata at SLAC
ts8MetadataPath: '/scratch/rubintv/ts8/sidecar_metadata'
ts8MetadataShardPath: '/scratch/rubintv/ts8/sidecar_metadata/shards'

# # paths for serving BOT metadata at SLAC
botMetadataPath: '/scratch/rubintv/LSSTCam/sidecar_metadata'
botMetadataShardPath: '/scratch/rubintv/LSSTCam/sidecar_metadata'

# configuration
binning: 8
