bucketName: rubintv_data

# Required items:
dataIdScanPath: /project/rubintv/dataIds
dimensionUniverseFile: /project/rubintv/butlerDimensionUniverse.json

# Summit items:
nightReportPath: /project/rubintv/nightReportData

# AuxTel
auxtelButlerPath: LATISS
auxTelMetadataPath: /project/rubintv/sidecar_metadata
auxTelMetadataShardPath: /project/rubintv/sidecar_metadata/shards

# all sky
allSkyRootDataPath: /project/rubintv/allsky/raw
allSkyOutputPath: /project/rubintv/allsky

# animation
moviePngPath: /project/rubintv/auxTel_animation

# Star Trackers paths:
# The path at which to find the data on disk. Does not include the
# GenericCamera/101/ or GenericCamera/102/ part, just the base directory.
starTrackerDataPath: /project
starTrackerOutputPath: /project/rubintv/starTracker/output
starTrackerMetadataPath: /project/rubintv/starTracker/sidecar_metadata
starTrackerMetadataShardPath: /project/rubintv/starTracker/sidecar_metadata/shards


# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
astrometryNetRefCatPath: /project/shared/ref_cats/astrometry_net

# ComCam configuration:
comCamButlerPath: /repo/LSSTComCam/butler.yaml
binning: 8
# # paths for serving TS8 metadata at SLAC
comCamMetadataPath: /project/rubintv/LSSTComCam/sidecar_metadata
comCamMetadataShardPath: /project/rubintv/LSSTComCam/sidecar_metadata/shards

comCamSimMetadataPath: /project/rubintv/LSSTComCamSim/sidecar_metadata
comCamSimMetadataShardPath: /project/rubintv/LSSTComCamSim/sidecar_metadata/shards

comCamSimAosMetadataPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata
comCamSimAosMetadataShardPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata/shards

comCamAosMetadataPath: /project/rubintv/LSSTComCamAos/sidecar_metadata
comCamAosMetadataShardPath: /project/rubintv/LSSTComCamAos/sidecar_metadata/shards

lsstCamMetadataPath: /project/rubintv/LSSTCam/sidecar_metadata
lsstCamMetadataShardPath: /project/rubintv/LSSTCam/sidecar_metadata/shards
lsstCamAosMetadataPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamAosMetadataShardPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamButlerPath: LSSTCam

# Not prefixed with ComCam because were currently just pretending that ComCam is TS8
scratchPath: /project/rubintv/
plotPath: /project/rubintv/plots
calculatedDataPath: /project/rubintv/calculatedData
binnedCalexpPath: /project/rubintv/calculatedData/calexps

# TMA config:
tmaMetadataPath: /project/rubintv/tma/sidecar_metadata
tmaMetadataShardPath: /project/rubintv/tma/sidecar_metadata/shards

sfmPipelineFile:
  LATISS: $ATMOSPEC_DIR/pipelines/processStar.yaml
  LSSTComCamSim: $DRP_PIPE_DIR/pipelines/LSSTComCamSim/quickLook.yaml
  LSSTComCam: $DRP_PIPE_DIR/pipelines/LSSTComCam/quickLook.yaml
  LSSTCam: $DRP_PIPE_DIR/pipelines/LSSTCam/quickLook.yaml

aosPipelineFile:
  LATISS: ''
  LSSTComCamSim: $TS_WEP_DIR/pipelines/production/comCamSimRapidAnalysisPipeline.yaml
  LSSTComCam: $TS_WEP_DIR/pipelines/production/comCamRapidAnalysisDanishPipeline.yaml
  LSSTCam: $TS_WEP_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_TIE.yaml

outputChains:
  LATISS: LATISS/quickLook
  LSSTComCam: LSSTComCam/quickLook
  LSSTComCamSim: LSSTComCamSim/quickLook
  LSSTCam: LSSTCam/quickLook
