# AuxTel metadata
auxTelMetadataPath: '/sdf/home/m/mfl/u/rubintv/sidecar_metadata'
auxTelMetadataShardPath: '/sdf/home/m/mfl/u/rubintv/sidecar_metadata/shards'

# all sky
allSkyRootDataPath: '/sdf/home/m/mfl/u/rubintv/allsky/raw'
allSkyOutputPath: '/sdf/home/m/mfl/u/rubintv/allsky'

# animation
moviePngPath: '/sdf/home/m/mfl/u/rubintv/auxTel_animation'

# Star Trackers paths:
# The path at which to find the data on disk. Does not include the
# GenericCamera/101/ or GenericCamera/102/ part, just the base directory.
# starTrackerDataPath: '/project'

# for writing the per-day json files and shards to for the star tracker channels
# starTrackerMetadataPath: '/sdf/home/m/mfl/u/rubintv/starTracker/sidecar_metadata'
# starTrackerMetadataShardPath: '/sdf/home/m/mfl/u/rubintv/starTracker/sidecar_metadata'

# for writing the rendered pngs of the a.net fits out to
# starTrackerOutputPath: '/sdf/home/m/mfl/u/rubintv/starTracker/output'

# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
astrometryNetRefCatPath: '/sdf/home/m/mfl/u/astrometry_net'

#######################
# SLAC paths and config
#######################

# Butler paths - use full paths not aliases here as path existence is checked
ts8ButlerPath: '/sdf/group/rubin/repo/ir2'
botButlerPath: '/sdf/group/rubin/repo/main'

# # data paths
scratchPath: '/sdf/home/m/mfl/u/rubintv/rubinTv'
dataIdScanPath: '/sdf/home/m/mfl/u/rubintv/rubinTv/dataIds'
plotPath: '/sdf/home/m/mfl/u/rubintv/rubinTv/plots'
binnedImagePath: '/sdf/home/m/mfl/u/rubintv/rubinTv/binnedImages'
# calculatedDataPath: '/sdf/home/m/mfl/u/rubintv/calculatedData'
calculatedDataPath: '/sdf/home/m/mfl/u/rubintv/rubinTv/calculatedData'

# # paths for serving TS8 metadata at SLAC
# ts8MetadataPath:       ''
# ts8MetadataShardPath:  ''

# # paths for serving BOT metadata at SLAC
# botMetadataPath:       ''
# botMetadataShardPath:  ''

# configuration
bucketName: 'rubintv_data'
binning: 8
