dataIdScanPath:     '/project/rubintv/dataIds'

# AuxTel metadata
auxTelMetadataPath: '/project/rubintv/sidecar_metadata'
auxTelMetadataShardPath: '/project/rubintv/sidecar_metadata/shards'

# all sky
allSkyRootDataPath: '/project/rubintv/allsky/raw'
allSkyOutputPath: '/project/rubintv/allsky'

# animation
moviePngPath: '/project/rubintv/auxTel_animation'

# Star Trackers paths:
# The path at which to find the data on disk. Does not include the
# GenericCamera/101/ or GenericCamera/102/ part, just the base directory.
starTrackerDataPath: '/project'

# for writing the per-day json files and shards to for the star tracker channels
starTrackerMetadataPath: '/project/rubintv/starTracker/sidecar_metadata'
starTrackerMetadataShardPath: '/project/rubintv/starTracker/sidecar_metadata'

# for writing the rendered pngs of the a.net fits out to
starTrackerOutputPath: '/project/rubintv/starTracker/output'

# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
astrometryNetRefCatPath: '/project/shared/ref_cats/astrometry_net'

#######################
# SLAC paths and config
#######################

# Butler paths - use full paths not aliases here as path existence is checked
# ts8ButlerPath: ''
# botButlerPath: ''

# # data paths
# scratchPath:        '/project/rubintv'
dataIdScanPath:     '/project/rubintv/dataIds'
# plotPath:           '/project/rubintv/plots'
# binnedImagePath:    '/project/rubintv/binnedImages'
# calculatedDataPath: '/project/rubintv/calculatedData'

# # paths for serving TS8 metadata at SLAC
# ts8MetadataPath:       ''
# ts8MetadataShardPath:  ''

# # paths for serving BOT metadata at SLAC
# botMetadataPath:       ''
# botMetadataShardPath:  ''

# configuration
bucketName: 'rubintv_data'
binning: 8
