# Required items:
bucketName: 'rubintv_data_tts'
dimensionUniverseFile: '/project/rubintv/butlerDimensionUniverse.json'

# Summit items:
nightReportPath:     '/project/rubintv/nightReportData'

# AuxTel
auxtelButlerPath: LATISS
auxTelMetadataPath: '/project/rubintv/sidecar_metadata'
auxTelMetadataShardPath: '/project/rubintv/sidecar_metadata/shards'

# all sky
allSkyRootDataPath: '/project/rubintv/allsky/raw'
allSkyOutputPath: '/project/rubintv/allsky'

# animation
moviePngPath: '/project/rubintv/auxTel_animation'

# The path to the astrometry.net reference catalogs. Do not include
# the /4100 or /4200, just the base directory.
# astrometryNetRefCatPath: '/project/shared/ref_cats/astrometry_net'

# ComCam configuration:
comCamButlerPath: /repo/LSSTComCam/butler.yaml
binning: 8

comCamMetadataPath: /project/rubintv/LSSTComCam/sidecar_metadata
comCamMetadataShardPath: /project/rubintv/LSSTComCam/sidecar_metadata/shards

comCamSimMetadataPath: /project/rubintv/LSSTComCamSim/sidecar_metadata
comCamSimMetadataShardPath: /project/rubintv/LSSTComCamSim/sidecar_metadata/shards

comCamSimAosMetadataPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata
comCamSimAosMetadataShardPath: /project/rubintv/LSSTComCamSimAos/sidecar_metadata/shards

comCamAosMetadataPath: /project/rubintv/LSSTComCamAos/sidecar_metadata
comCamAosMetadataShardPath: /project/rubintv/LSSTComCamAos/sidecar_metadata/shards

raPerformanceDirectory: /project/rubintv/raPerformance/sidecar_metadata
raPerformanceShardsDirectory: /project/rubintv/raPerformance/sidecar_metadata/shards

lsstCamMetadataPath: /project/rubintv/LSSTCam/sidecar_metadata
lsstCamMetadataShardPath: /project/rubintv/LSSTCam/sidecar_metadata/shards
lsstCamAosMetadataPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamAosMetadataShardPath: /project/rubintv/LSSTCamAos/sidecar_metadata/shards
lsstCamButlerPath: /repo/LSSTCam/butler.yaml

scratchPath: '/project/rubintv/LSSTComCam'
plotPath: '/project/rubintv/LSSTComCam/plots'
calculatedDataPath: '/project/rubintv/calculatedData'
binnedVisitImagePath: /project/rubintv/calculatedData/visitImages

# TMA config:
tmaMetadataPath: '/project/rubintv/tma/sidecar_metadata'
tmaMetadataShardPath: '/project/rubintv/tma/sidecar_metadata/shards'

consDBURL: "http://consdb-pq.consdb:8080/consdb"

aosLSSTCamPipelineFileDanish: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_Danish.yaml
aosLSSTCamPipelineFileTie: $DONUT_VIZ_DIR/pipelines/production/lsstCamRapidAnalysisPipeline_TIE.yaml

aosLSSTCamFullArrayModePipelineFileDanish: $DONUT_VIZ_DIR/pipelines/production/lsstCamScienceSensorRapidAnalysisPipeline_Danish.yaml
aosLSSTCamFullArrayModePipelineFileTie: $DONUT_VIZ_DIR/pipelines/production/lsstCamScienceSensorRapidAnalysisPipeline_TIE.yaml

sfmPipelineFile:
  LATISS: $ATMOSPEC_DIR/pipelines/processStar.yaml
  LSSTComCamSim: $DRP_PIPE_DIR/pipelines/LSSTComCamSim/quickLook.yaml
  LSSTComCam: $DRP_PIPE_DIR/pipelines/LSSTComCam/quickLook.yaml
  LSSTCam: $DRP_PIPE_DIR/pipelines/LSSTCam/quickLook.yaml

aosPipelineFile:
  LATISS: ''
  LSSTComCamSim: $DONUT_VIZ_DIR/pipelines/production/comCamSimRapidAnalysisPipeline.yaml
  LSSTComCam: $DONUT_VIZ_DIR/pipelines/production/comCamRapidAnalysisPipeline.yaml

outputChains:
  LATISS: LATISS/runs/quickLook
  LSSTComCam: LSSTComCam/runs/quickLook
  LSSTComCamSim: LSSTComCamSim/runs/quickLook
  LSSTCam: LSSTCam/runs/quickLook


### not applicable on the TTS but here explicitly to keep keys the same:
# they also need to exist for the LocationConfig to init correctly as it checks
starTrackerDataPath: '/project'
starTrackerOutputPath: '/project'
starTrackerMetadataShardPath: '/project'
starTrackerMetadataPath: '/project'
astrometryNetRefCatPath: '/project'
