# metadata
metadataOutputRoot: "/project/rubintv/sidecar_metadata/"

# all sky
allSkyRootDataPath: "/project/rubintv/allsky/raw/"
allSkyOutputRoot: "/project/rubintv/allsky/"

# animation
moviePngRoot: "/project/rubintv/auxTel_animation/"

# Star Trackers
starTrackerDataPath: "/sdf/home/m/mfl/u/starTracker/"  # XXX correct this
starTrackerMetadataRoot: "/sdf/group/rubin/u/mfl/rubintv/starTracker/sidecar_metadata/"
starTrackerOutputRoot: "/sdf/group/rubin/u/mfl/rubintv/starTracker/output/"
