# Required items:
dataIdScanPath: '/sdf/scratch/rubin/rapid-analysis/dataIds'
bucketName: 'rubintv_data_slac'
dimensionUniverseFile: '/sdf/scratch/rubin/rapid-analysis/butlerDimensionUniverse.json'

# Butler paths - use full paths not aliases here as path existence is checked
ts8ButlerPath: '/sdf/group/rubin/repo/ir2/butler.yaml'
botButlerPath: '/sdf/group/rubin/repo/ir2/butler.yaml'

# # data paths
scratchPath: ''
plotPath: '/sdf/scratch/rubin/rapid-analysis/plots'
calculatedDataPath: '/sdf/scratch/rubin/rapid-analysis/calculatedData'
binnedCalexpPath: '/sdf/scratch/rubin/rapid-analysis/calculatedData/calexps'

# # paths for serving TS8 metadata at SLAC
ts8MetadataPath: '/sdf/scratch/rubin/rapid-analysis/ts8/sidecar_metadata'
ts8MetadataShardPath: '/sdf/scratch/rubin/rapid-analysis/ts8/sidecar_metadata/shards'

# # paths for serving BOT metadata at SLAC
botMetadataPath: '/sdf/scratch/rubin/rapid-analysis/LSSTCam/sidecar_metadata'
botMetadataShardPath: '/sdf/scratch/rubin/rapid-analysis/LSSTCam/sidecar_metadata'

# configuration
binning: 8

# ComCam configuration:
comCamButlerPath: '/sdf/group/rubin/repo/embargo/butler+sasquatch_dev.yaml'
# # paths for serving TS8 metadata at SLAC
comCamMetadataPath: '/sdf/scratch/rubin/rapid-analysis/LSSTComCam/sidecar_metadata'
comCamMetadataShardPath: '/sdf/scratch/rubin/rapid-analysis/LSSTComCam/sidecar_metadata/shards'

# Redis work distribution configs
sfmPipelineFile: '$DRP_PIPE_DIR/pipelines/LSSTComCamSim/nightly-validation.yaml'

outputChains:
  LSSTComCam: LSSTComCam/nightlyValidation
  LSSTComCamSim: LSSTComCamSim/nightlyValidation
  LSSTCam: LSSTCam/nightlyValidation

comCamSimMetadataPath: '/sdf/scratch/rubin/rapid-analysis/LSSTComCamSim/sidecar_metadata'
comCamSimMetadataShardPath: '/sdf/scratch/rubin/rapid-analysis/LSSTComCamSim/sidecar_metadata/shards'
