# Required items:
dataIdScanPath: '/sdf/scratch/rubintv/dataIds'
bucketName: 'rubintv_data_slac'
dimensionUniverseFile: '/sdf/scratch/rubintv/butlerDimensionUniverse.json'

# Butler paths - use full paths not aliases here as path existence is checked
ts8ButlerPath: '/sdf/group/rubin/repo/ir2/butler.yaml'
botButlerPath: '/sdf/group/rubin/repo/ir2/butler.yaml'

# # data paths
scratchPath: '/sdf/scratch/rubintv'
plotPath: '/sdf/scratch/rubintv/plots'
calculatedDataPath: '/sdf/scratch/rubintv/calculatedData'

# # paths for serving TS8 metadata at SLAC
ts8MetadataPath: '/sdf/scratch/rubintv/ts8/sidecar_metadata'
ts8MetadataShardPath: '/sdf/scratch/rubintv/ts8/sidecar_metadata/shards'

# # paths for serving BOT metadata at SLAC
botMetadataPath: '/sdf/scratch/rubintv/LSSTCam/sidecar_metadata'
botMetadataShardPath: '/sdf/scratch/rubintv/LSSTCam/sidecar_metadata'

# configuration
binning: 8
