# Required items:
dataIdScanPath: '/sdf/scratch/rubin/rapid-analysis/dataIds'
bucketName: 'rubintv_data_slac'

# Butler paths - use full paths not aliases here as path existence is checked
butlerPath: '/sdf/group/rubin/repo/embargo/butler.yaml'

# # data paths
scratchPath: '/sdf/scratch/rubin/rapid-analysis'
plotPath: '/sdf/scratch/rubin/rapid-analysis/plots'
calculatedDataPath: '/sdf/scratch/rubin/rapid-analysis/calculatedData'

# # paths for serving BOT metadata at SLAC
metadataPath: '/sdf/scratch/rubin/rapid-analysis/LSSTComCamSim/sidecar_metadata'
metadataShardPath: '/sdf/scratch/rubin/rapid-analysis/LSSTCamSim/sidecar_metadata'

# configuration
binning: 8
